### ISSUE TITLE
server rejected WebSocket connection

### ISSUE THREAD

**Issue by Eikosa** [p4kl0nc4t/kyros#32]
```
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wp test.py", line 40, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\USER\Desktop\wp test.py", line 14, in main
    whatsapp = await kyros.Client.create()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\kyros\client.py", line 32, in create
    await instance.setup_ws()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\kyros\client.py", line 54, in setup_ws
    await self.websocket.connect()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\kyros\websocket.py", line 145, in connect
    constants.WEBSOCKET_URI, origin=constants.WEBSOCKET_ORIGIN)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Program Files\Python37\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\client.py", line 664, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404
```

**Comment by lc-at** [comment]
This project is no longer maintained. Please look for other alternatives.
